[project]
name = "union-work"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "docxtpl>=0.19.1",
    "freesimplegui>=5.2.0.post1",
    "python-docx>=1.1.2",
    "xlsxwriter>=3.2.3",
]
